sudo: false
language: node_js
node_js:
- '12'
branches:
  only:
  - master
before_deploy:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: cdc.hitcon.org
  local_dir: dist/
  on:
    branch: master
